<?php

$sLangName = "English";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(
    'charset'                                           => 'UTF-8',

    /* SETTINGS */
    'SHOP_MODULE_GROUP_MOLLIE_GENERAL'                  => 'Basic configuration',
    'SHOP_MODULE_sMollieMode'                           => 'Mode',
    'SHOP_MODULE_sMollieMode_live'                      => 'Live',
    'SHOP_MODULE_sMollieMode_test'                      => 'Test',
    'SHOP_MODULE_sMollieTestToken'                      => 'Test API Key',
    'SHOP_MODULE_sMollieLiveToken'                      => 'Live API Key',
    'SHOP_MODULE_blMollieShowIcons'                     => 'Show icons',
    'SHOP_MODULE_blMollieLogTransactionInfo'            => 'Log result of transaction handling',
    'SHOP_MODULE_blMollieRemoveDeactivatedMethods'      => 'Remove deactivated payment types',
    'SHOP_MODULE_sMollieStatusPending'                  => 'Status Pending',
    'SHOP_MODULE_sMollieStatusProcessing'               => 'Status Processing',

    'HELP_SHOP_MODULE_blMollieShowIcons'                => 'Show Payment Icons on Checkout',
    'HELP_SHOP_MODULE_blMollieLogTransactionInfo'       => 'Log file to be found here: SHOPROOT/log/MollieTransactions.log',
    'HELP_SHOP_MODULE_blMollieRemoveDeactivatedMethods' => 'Removes the payment types from the frontend payment selection which are not activated in the Mollie Dashboard and thus would result in an error.',
    'HELP_SHOP_MODULE_sMollieStatusPending'             => 'Set the order status before the customer is redirected to Payment Gateway',
    'HELP_SHOP_MODULE_sMollieStatusProcessing'          => 'Set the order status for Completed Payments',

    'MOLLIE_YES'                                        => 'Yes',
    'MOLLIE_NO'                                         => 'No',
    'MOLLIE_IS_MOLLIE'                                  => 'This is a Mollie payment type',
    'MOLLIE_IS_METHOD_ACTIVATED'                        => 'This payment type is not activated in your Mollie account!',
    'MOLLIE_TOKEN_NOT_CONFIGURED'                       => 'Your Mollie token was not configured yet!',
    'MOLLIE_CONFIG_METHOD'                              => 'API method',
    'MOLLIE_DUE_DATE'                                   => 'Due days',
    'MOLLIE_BANKTRANSFER_PENDING'                       => 'Status Pending',
    'MOLLIE_LIST_STYLE'                                 => 'Issuer List Style',
    'MOLLIE_LIST_STYLE_DROPDOWN'                        => 'Dropdown',
    'MOLLIE_LIST_STYLE_IMAGES'                          => 'List with images',
    'MOLLIE_LIST_STYLE_DONT_SHOW'                       => 'Don\'t show issuer list',
    'MOLLIE_ADD_QR'                                     => 'Add QR-Code option in Issuer List',
    'MOLLIE_ORDER_REFUND'                               => 'Mollie',
    'MOLLIE_REFUND_SUCCESSFUL'                          => 'Refund was successful.',
    'MOLLIE_NO_MOLLIE_PAYMENT'                          => 'This order was not payed with Mollie.',
    'MOLLIE_REFUND_QUANTITY'                            => 'Refund quantity',
    'MOLLIE_REFUND_AMOUNT'                              => 'Refund amount',
    'MOLLIE_TYPE_SELECT_LABEL'                          => 'Refund by',
    'MOLLIE_QUANTITY'                                   => 'Quantity',
    'MOLLIE_NOTICE'                                     => 'Notice',
    'MOLLIE_AMOUNT'                                     => 'Amount',
    'MOLLIE_HEADER_ORDERED'                             => 'Ordered',
    'MOLLIE_HEADER_REFUNDED'                            => 'Refunded',
    'MOLLIE_HEADER_SINGLE_PRICE'                        => 'Unitprice',
    'MOLLIE_SHIPPINGCOST'                               => "Shipping cost",
    'MOLLIE_PAYMENTTYPESURCHARGE'                       => "Payment surcharge",
    'MOLLIE_WRAPPING'                                   => "Giftwrapping",
    'MOLLIE_GIFTCARD'                                   => "Greeting card",
    'MOLLIE_VOUCHER'                                    => 'Voucher',
    'MOLLIE_DISCOUNT'                                   => 'Discount',
    'MOLLIE_REFUND_SUBMIT'                              => 'Execute refund',
    'MOLLIE_FULL_REFUND'                                => 'Full refund',
    'MOLLIE_PARTIAL_REFUND'                             => 'Partial refund',
    'MOLLIE_FULL_REFUND_TEXT'                           => 'Execute full refund with the amount of',
    'MOLLIE_FULL_REFUND_NOT_AVAILABLE'                  => 'A full refund is not available for this order anymore, there were partial refunds already.',
    'MOLLIE_REFUND_DESCRIPTION'                         => 'Refund notice',
    'MOLLIE_REFUND_DESCRIPTION_PLACEHOLDER'             => 'optional - max 140 characters',
    'MOLLIE_REFUND_FREE_AMOUNT'                         => 'Free refund amount',
    'MOLLIE_REFUND_FREE_1'                              => 'Of the total price of',
    'MOLLIE_REFUND_FREE_2'                              => ',',
    'MOLLIE_REFUND_FREE_3'                              => 'have already been refunded. Remaining refundable amount',
    'MOLLIE_ORDER_NOT_REFUNDABLE'                       => 'This order has been refunded completely already.',
    'MOLLIE_REFUND_REMAINING'                           => 'Refund remaining sum',
    'MOLLIE_VOUCHERS_EXISTING'                          => 'This order includes vouchers or discount. These cant be refunded partially, they must be handled with the full or remaining refund.',
    'MOLLIE_CREDITCARD_DATA_INPUT'                      => 'Creditcard data',
    'MOLLIE_CC_HOSTED_CHECKOUT'                         => 'Input on external Mollie website',
    'MOLLIE_CC_CHECKOUT_INTEGRATION'                    => 'Input in shop checkout with iframe form inputs',
    'MOLLIE_APPLE_PAY_BUTTON_ONLY_LIVE_MODE'            => 'Please note: Payment with the Apple Pay Button is only available in live-mode.'
);
